FROM wurstmeister/zookeeper:latest

# COPY zookeeper.properties /etc/kafka/zookeeper.properties

EXPOSE 2181/tcp

ENV ZOOKEEPER_CLIENT_PORT=2181
ENV ZOOKEEPER_TICK_TIME=2000
# ENV ZOOKEEPER_SYNC_LIMIT=2