apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-redis
  labels:
    app: data-redis
spec:
  selector:
    matchLabels:
      app: data-redis
  template:
    metadata:
      labels:
        app: data-redis
    spec:
      containers:
        - name: data-redis
          image: public.ecr.aws/docker/library/redis:7
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis-server
              containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: data-redis
  labels:
    app: data-redis
spec:
  ports:
    - port: 6379
      targetPort: redis-server
  selector:
    app: data-redis
  type: NodePort
