apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: public.ecr.aws/docker/library/postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres-server
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: postgres-schemma-volume
              mountPath: /docker-entrypoint-initdb.d/pginit.sql
              subPath: pginit.sql
              readOnly: true
      volumes:
      - name: postgres-schemma-volume
        configMap:
          name: postgres-schemma
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: postgres-server
  selector:
    app: postgres
  type: NodePort
