apiVersion: batch/v1
kind: Job
metadata:
  name: ping-redis
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: ping-redis
        image: redis:7
        env:
          - name: REDISCLI_URL
            value: "redis://redis.default.svc.cluster.local:6379/0"
        command: ["sh", "-c", "redis-cli -u $REDISCLI_URL ping"]
      restartPolicy: Never
  backoffLimit: 0