apiVersion: "v1"
kind: Pod
metadata:
  name: scraper-foreign-example-yahoofinance
spec:
  containers:
  - name: scraper-foreign-example-yahoofinance
    image: dia.genericforeignscraper.dev:latest
    imagePullPolicy: Never
    # command: ["foreignscraper"]
    # args: ["-foreignType=YahooFinance"]
    command: ["tail"]
    args: [ "-f", "/dev/null" ]
    env:
    - name: USE_ENV
      value: "true"
    - name: POSTGRES_USER
      value: "postgres"
    - name: POSTGRES_PASSWORD
      value: "password"
    - name: POSTGRES_DB
      value: "postgres"
    - name: POSTGRES_HOST
      value: "data-postgres.default.svc.cluster.local"
    - name: INFLUXURL
      value: "http://data-influx.default.svc.cluster.local:8086"
    - name: INFLUXUSER
      value: "test"
    - name: INFLUXPASSWORD
      value: "testtest"
    - name: REDISURL
      value: "data-redis.default.svc.cluster.local:6379"
    - name: KAFKAURL
      value: "data-kafka.default.svc.cluster.local:9094"
    - name: CURRENCIES_LIST_YAHOO
      value: "USDIDR=X:USD-IDR,USDSGD=X:USD-SGD,USDHKD=X:USD-HKD,USDMYR=X:USD-MYR,TZS=X:USD-TZS,EURTZS=X:EUR-TZS,TRY=X:USD-TRY,EURTRY=X:EUR-TRY,NGN=X:USD-NGN,BRL=X:USD-BRL,ARS=X:USD-ARS,AED=X:USD-AED,TWD=X:USD-TWD,USDZAR=X:USD-ZAR,USDCNY=X:USD-CNY,USDJPY=X:USD-JPY,USDPHP=X:USD-PHP,USDTHB=X:USD-THB,USDRUB=X:USD-RUB,USDINR=X:USD-INR,USDTRY=X:USD-TRY,EURGBP=X:EUR-GBP,CNY=X:USD-CNY,MXN=X:USD-MXN,ZAR=X:USD-ZAR,RUB=X:USD-RUB,JPY=X:USD-JPY,PHP=X:USD-PHP,HKD=X:USD-HKD,SGD=X:USD-SGD,INR=X:USD-INR,IDR=X:USD-IDR,THB=X:USD-THB,MYR=X:USD-MYR,EURUSD=X:EUR-USD,EURJPY=X:EUR-JPY,GBPJPY=X:GBP-JPY,GBPUSD=X:GBP-USD,AUDUSD=X:AUD-USD,NZDUSD=X:NZD-USD,EURCAD=X:EUR-CAD,EURSEK=X:EUR-SEK,EURCHF=X:EUR-CHF,EURHUF=X:EUR-HUF"
    volumeMounts:
    - name: env-context
      mountPath: /mnt/env-context
      readOnly: true
  initContainers:
  - name: check-postgres-connection
    image: public.ecr.aws/docker/library/postgres:15-alpine
    env:
    - name: PGHOST
      value: "data-postgres.default.svc.cluster.local"
    - name: PGUSER
      value: "postgres"
    - name: PGPASSWORD
      value: "password"
    command: ["sh", "-c", "until pg_isready -h $PGHOST -U $PGUSER; do sleep 1; done"]
  - name: check-redis-connection
    image: public.ecr.aws/docker/library/redis:7
    env:
    - name: REDISCLI_URL
      value: "redis://data-redis.default.svc.cluster.local:6379/0"
    command: ["sh", "-c", "until redis-cli -u $REDISCLI_URL ping; do sleep 1; done"]
  - name: check-influxdb-connection
    image: public.ecr.aws/docker/library/influxdb:1.8
    env:
    - name: INFLUXDB_URL
      value: "data-influx.default.svc.cluster.local"
    - name: INFLUXDB_USERNAME
      value: "test"
    - name: INFLUXDB_PASSWORD
      value: "testtest"
    command: ["sh", "-c", "until influx -host $INFLUXDB_URL -username $INFLUXDB_USERNAME -password $INFLUXDB_PASSWORD -execute 'SHOW DATABASES'; do sleep 1; done"]
  - name: check-kafka-connection
    image: confluentinc/cp-kafkacat:6.2.1
    env:
    - name: KAFKA_BROKER_URL
      value: "data-kafka.default.svc.cluster.local:9094"
    command: ["sh", "-c", "until kafkacat -b $KAFKA_BROKER_URL -L; do sleep 1; done"]
  volumes:
  - name: env-context
    hostPath:
      path: /mnt/diadata