apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-cron
  labels:
    app: postgres-cron
spec:
  schedule: "*/7 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-cron
              image: gcr.io/kaniko-project/executor
              imagePullPolicy: IfNotPresent
              args:
                - "--dockerfile=/kaniko-dockerfile/Dockerfile-postgres"
                - "--context=/kaniko-context"
                - "--destination=diadata.postgres:latest"
              volumeMounts:
              - name: postgres-cron-dockerfile
                mountPath: /kaniko-dockerfile
          volumes:
          - name: postgres-cron-dockerfile
            configMap:
              name: postgres-cron-dockerfile
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=<path to Dockerfile within the build context>"
        - "--context=gs://<GCS bucket>/<path to .tar.gz>"
        - "--destination=<gcr.io/$PROJECT/$IMAGE:$TAG>"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret
        - name: postgres-context
          mountPath: /postgres-context
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
    - name: postgres-context
      configMap:
        name: postgres-context