apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-db-influx"
  labels:
    app: diadata-clusterdev-db-influx
spec:
  containers:
  - name: clusterdev-db-influx
    image: influxdb:1.8
    # image: influxdb:2.6
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8086
      - containerPort: 8088
    command: ["influxd", "-config", "/etc/influxdb/influxdb.conf"]
    # TODO: influx 2
    # command: ["influxd"]
    env:
      - name: INFLUXDB_HTTP_MAX_BODY_SIZE
        value: "0"
      - name: INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE
        value: "4g"
      - name: INFLUXDB_DATA_MAX_INDEX_LOG_FILE_SIZE
        value: "8m"
      - name: DOCKER_INFLUXDB_INIT_MODE
        value: "setup"
      - name: DOCKER_INFLUXDB_INIT_USERNAME
        value: "diadata_user"
      - name: DOCKER_INFLUXDB_INIT_PASSWORD
        value: "diadata_pw"
      - name: DOCKER_INFLUXDB_INIT_ORG
        value: "diadata"
      - name: DOCKER_INFLUXDB_INIT_BUCKET
        value: "diadata_b"
      - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
        value: "diadata_token"
    volumeMounts:
    - name: influx-config
      mountPath: /etc/influxdb/influxdb.conf
      subPath: influxdb.conf
      readOnly: true
    resources:
      limits:
        memory: 512Mi
        cpu: 2
      requests:
        memory: 100Mi
        cpu: 100m
  volumes:
  - name: influx-config
    configMap:
      name: influx-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: clusterdev-db-influx-service
spec:
  selector:
    app: diadata-clusterdev-db-influx
  ports:
    - name: influx
      protocol: TCP
      port: 8086
      targetPort: 8086