apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-db-kafka"
  labels:
    app: diadata-clusterdev-db-kafka
spec:
  containers:
  - name: clusterdev-db-zookeeper
    image: wurstmeister/zookeeper:latest
    env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: ZOOKEEPER_TICK_TIME
      value: "2000"
    resources:
      limits:
        memory: 512Mi
        cpu: 2
      requests:
        memory: 100Mi
        cpu: 100m
  - name: clusterdev-db-kafka
    image: wurstmeister/kafka:latest
    env:
    - name: HOSTNAME_COMMAND
      value: "docker info | grep ^Name: | cut -d' ' -f 2"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "localhost:2181"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "INSIDE://:9092,OUTSIDE://clusterdev-db-kafka-service.default.svc.cluster.local:9094"
    - name: KAFKA_LISTENERS
      value: "INSIDE://:9092,OUTSIDE://:9094"
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: "INSIDE"
    - name: KAFKA_LOG_DIRS
      value: "/kafka/kafka-logs-1"
    - name: KAFKA_DELETE_TOPIC_ENABLE
      value: "true"
    - name: KAFKA_MESSAGE_MAX_BYTES
      value: "50000000"
  - name: clusterdev-db-kafka-ui
    image: tchiotludo/akhq:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: akhq-config
      mountPath: /app/application.yml
      subPath: akhq.yaml
      readOnly: true
  volumes:
  - name: akhq-config
    configMap:
      name: akhq-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: clusterdev-db-kafka-service
spec:
  selector:
    app: diadata-clusterdev-db-kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9094
      targetPort: 9094
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181