apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-http-restserver"
spec:
  containers:
  - name: clusterdev-http-restserver
    image: dia-http-restserver:0.1
    command: ["restServer"]
    args: ["-replayInflux=false", "-historical=true", "-testing=true"]
    env:
    - name: USE_ENV
      value: "true"
    - name: POSTGRES_USER
      value: "diadata_psql_user"
    - name: POSTGRES_PASSWORD
      value: "diadata_psql_pass"
    - name: POSTGRES_DB
      value: "diadata_psql_db"
    - name: POSTGRES_HOST
      value: "clusterdev-db-postgres-service.default.svc.cluster.local"
    - name: INFLUXURL
      value: "http://clusterdev-db-influx-service.default.svc.cluster.local:8086"
    - name: INFLUXUSER
      value: "diadata_user"
    - name: INFLUXPASSWORD
      value: "diadata_pw"
    - name: REDISURL
      value: "clusterdev-db-redis-service.default.svc.cluster.local:6379"
    - name: KAFKAURL
      value: "clusterdev-db-kafka-service.default.svc.cluster.local:9094"