apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: zookeep-server
              containerPort: 2181
          env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
        - name: kafka
          image: wurstmeister/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: kafka-server
              containerPort: 9094
          env:
          - name: HOSTNAME_COMMAND
            value: "docker info | grep ^Name: | cut -d' ' -f 2"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "localhost:2181"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "INSIDE://:9092,OUTSIDE://kafka.default.svc.cluster.local:9094"
          - name: KAFKA_LISTENERS
            value: "INSIDE://:9092,OUTSIDE://:9094"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "INSIDE"
          - name: KAFKA_LOG_DIRS
            value: "/kafka/kafka-logs-1"
          - name: KAFKA_DELETE_TOPIC_ENABLE
            value: "true"
          - name: KAFKA_MESSAGE_MAX_BYTES
            value: "50000000"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9094
      targetPort: kafka-server
      name: kafka-server
    - port: 2181
      targetPort: zookeep-server
      name: zookeep-server
  selector:
    app: kafka
  type: NodePort