apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: diadata.postgres:latest
          imagePullPolicy: Never
          ports:
            - name: postgres-server
              containerPort: 5432
          command: ["docker-entrypoint.sh", "-c", "config_file=/etc/postgresql/postgresql.conf"]
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
          - name: postgres-config
            mountPath: /etc/postgresql/postgresql.conf
            subPath: postgresql.conf
            readOnly: true
          - name: postgres-config
            mountPath: /docker-entrypoint-initdb.d/pginit.sql
            subPath: pginit.sql
            readOnly: true
      volumes:
      - name: postgres-config
        configMap:
          name: postgres-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: postgres-server
  selector:
    app: postgres
  type: NodePort
