apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: proxy
    database: dia
    user: grafana
    url: http://clusterdev-db-influx-service.default.svc.cluster.local:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: grafana