apiVersion: 1

datasources:
  - name: InfluxDB_v1
    type: influxdb
    access: proxy
    database: dia
    user: diadata_user
    url: http://clusterdev-db-influx-service.default.svc.cluster.local:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: diadata_pw
  - name: Postgres
    type: postgres
    url: clusterdev-db-postgres-service.default.svc.cluster.local:5432
    user: diadata_psql_user
    database: diadata_psql_db
    secureJsonData:
      password: 'diadata_psql_pass'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false
