apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-db-influx"
  labels:
    app: diadata-clusterdev-db-influx
spec:
  containers:
  - name: clusterdev-db-influx
    image: diadata-clusterdev-db-influx:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: clusterdev-db-influx-service
spec:
  selector:
    app: diadata-clusterdev-db-influx
  ports:
    - name: influx
      protocol: TCP
      port: 8086
      targetPort: 8086