apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-db-kafka"
spec:
  containers:
  - name: clusterdev-db-kafka
    image: diadata-clusterdev-db-kafka:0.1
    env:
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "localhost:2181"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://localhost:9092"