apiVersion: v1
kind: ConfigMap
metadata:
  name: diadata-clusterdev-db-zookeeper-config
data:
  zookeeper.properties: |
    dataDir=/var/lib/zookeeper/data
    clientPort=2181
    maxClientCnxns=0
    tickTime=2000
    initLimit=10
    syncLimit=5
---
# apiVersion: "v1"
# kind: Pod
# metadata:
#   name: "diadata-clusterdev-db-kafka"
#   labels:
#     app: diadata-clusterdev-db-kafka
# spec:
#   containers:
#   - name: clusterdev-db-kafka
#     image: diadata-clusterdev-db-kafka:0.1
# ---
apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-db-kafka"
  labels:
    app: diadata-clusterdev-db-kafka
spec:
  containers:
  - name: clusterdev-db-zookeeper
    image: diadata-clusterdev-db-zookeeper:0.1
    # volumeMounts:
    #   - name: diadata-clusterdev-db-zookeeper-volume-config
    #     mountPath: /etc/kafka/
  - name: clusterdev-db-kafka
    image: diadata-clusterdev-db-kafka:0.1
    # env:
    # - name: KAFKA_ZOOKEEPER_CONNECT
    #   value: "localhost:2181"
    # - name: KAFKA_ADVERTISED_LISTENERS
    #   value: "PLAINTEXT://localhost:9092"
  volumes:
    - name: diadata-clusterdev-db-zookeeper-volume-config
      configMap:
        name: diadata-clusterdev-db-zookeeper-config
---
apiVersion: v1
kind: Service
metadata:
  name: clusterdev-db-kafka-service
spec:
  selector:
    app: diadata-clusterdev-db-kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9094
      targetPort: 9094
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181