# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgres-credentials
# type: Opaque
# data:
#   POSTGRES_USER: diadata_psql_user
#   POSTGRES_PASSWORD: diadata_psql_pass
#   POSTGRES_DB: diadata_psql_db
# ---
apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-db-postgres"
  labels:
    app: diadata-clusterdev-db-postgres
spec:
  containers:
  - name: clusterdev-db-postgres
    image: diadata-clusterdev-db-postgres:0.1
    # env:
    # - name: POSTGRES_USER
    #   valueFrom:
    #     secretKeyRef:
    #       name: postgres-credentials
    #       key: POSTGRES_USER
    # - name: POSTGRES_DB
    #   valueFrom:
    #     secretKeyRef:
    #       name: postgres-credentials
    #       key: POSTGRES_DB
    # - name: POSTGRES_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: postgres-credentials
    #       key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: clusterdev-db-postgres-service
spec:
  selector:
    app: diadata-clusterdev-db-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432