apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-db-redis"
  labels:
    app: diadata-clusterdev-db-redis
spec:
  containers:
  - name: clusterdev-db-redis
    image: diadata-clusterdev-db-redis:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: clusterdev-db-redis-service
spec:
  selector:
    app: diadata-clusterdev-db-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379