apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-db-redis"
  labels:
    app: diadata-clusterdev-db-redis
spec:
  containers:
  - name: clusterdev-db-redis
    image: redis:7
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 6379
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumeMounts:
    - name: redis-config
      mountPath: /usr/local/etc/redis/redis.conf
      subPath: redis.conf
      readOnly: true
  volumes:
  - name: redis-config
    configMap:
      name: redis-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: clusterdev-db-redis-service
spec:
  selector:
    app: diadata-clusterdev-db-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379