apiVersion: v1
kind: ConfigMap
metadata:
  name: diadata-clusterdev-db-zookeeper-config
data:
  zookeeper.properties: |
    dataDir=/var/lib/zookeeper/data
    clientPort=2181
    maxClientCnxns=0
    tickTime=2000
    initLimit=10
    syncLimit=5
---
apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-db-zookeeper"
  labels:
    app: diadata-clusterdev-db-zookeeper
spec:
  containers:
  - name: clusterdev-db-zookeeper
    image: diadata-clusterdev-db-zookeeper:0.1
    # volumeMounts:
    #   - name: diadata-clusterdev-db-zookeeper-volume-config
    #     mountPath: /etc/kafka/
  volumes:
    - name: diadata-clusterdev-db-zookeeper-volume-config
      configMap:
        name: diadata-clusterdev-db-zookeeper-config
---
apiVersion: v1
kind: Service
metadata:
  name: clusterdev-db-zookeeper-service
spec:
  selector:
    app: diadata-clusterdev-db-zookeeper
  ports:
    - name: zookeeper
      protocol: TCP
      port: 2181
      targetPort: 2181