apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-exchangescraper-collector-bittrex"
spec:
  containers:
  - name: clusterdev-exchangescraper-collector-bittrex
    image: diadata-clusterdev-exchangescraper-collector:0.1
    command: ["collector"]
    args: ["-exchange=Bittrex", "-mode=storeTrades", "-pairsfile=true"]