apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-exchangescraper-collector-bitmax"
spec:
  containers:
  - name: clusterdev-exchangescraper-collector-bitmax
    image: diadata-clusterdev-exchangescraper-collector:0.1
    command: ["collector"]
    args: ["-exchange=Bitmax", "-mode=storeTrades", "-pairsfile=true"]