apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-exchangescraper-collector-crex24"
spec:
  containers:
  - name: clusterdev-exchangescraper-collector-crex24
    image: diadata-clusterdev-exchangescraper-collector:0.1
    command: ["collector"]
    args: ["-exchange=CREX24", "-pairsfile=true"]