apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-exchangescraper-collector-quoine"
spec:
  containers:
  - name: clusterdev-exchangescraper-collector-quoine
    image: diadata-clusterdev-exchangescraper-collector:0.1
    command: ["collector"]
    args: ["-exchange=Quoine", "-mode=storeTrades", "-pairsfile=true"]