apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-exchangescraper-collector-kucoin"
spec:
  containers:
  - name: clusterdev-exchangescraper-collector-kucoin
    image: diadata-clusterdev-exchangescraper-collector:0.1
    command: ["collector"]
    args: ["-exchange=KuCoin", "-mode=storeTrades", "-pairsfile=true"]