apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-exchangescraper-collector-mexc"
spec:
  containers:
  - name: clusterdev-exchangescraper-collector-mexc
    image: diadata-clusterdev-exchangescraper-collector:0.1
