apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-service-filtersblockservice"
spec:
  containers:
  - name: clusterdev-service-filtersblockservice
    image: diadata-clusterdev-service-filtersblockservice:0.1
    command: ["filtersBlockService"]
    args: ["-replayInflux=false", "-historical=true", "-testing=true"]