apiVersion: "v1"
kind: Pod
metadata:
  name: "diadata-clusterdev-service-tradesblockservice"
spec:
  containers:
  - name: clusterdev-service-tradesblockservice
    image: diadata-clusterdev-service-tradesblockservice:0.1
    command: ["tradesBlockService"]
    args: ["-historical=true", "-testing=true"]